name: Test_java
on:
  pull_request:
    paths: ['src/**/*.java']
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        working-directory: .
      - name: Test with Maven
        run: mvn --batch-mode test
        working-directory: .
